### PR TITLE
Update check-button-card.ts

### PR DESCRIPTION
**Pull request by jeremywillans**
Fix timestamp calculation from manual input

### CODE REVIEW

**Comment by jeremywillans** [comment]
@Gluwc,

I have added an option to disable the unit-of-measurment. This is to allow the history state to work for the past 24 hours from the more-info popup.

Another use of this card for me is monitoring medicine and quickly accessing last 24 hours of state changes is ideal

Current - 
image

Updated with Unit disabled - 
image

**Comment by Gluwc** [comment]
Maybe the `unit_of_measurement` should just be removed all together. However it currently uses that to determine if the sensor is a `check-button-card` sensor or not. Maybe there's another way to determine if the sensor is a `check-button-card`, that doesn't break the cards that have already been set up.

**Comment by jeremywillans** [comment]
I added a new attribute ‘’’type’’’ which the same checks but only applies if unit is set to false. This means that existing cards continue to work as-is and need to be re-setup if they want to remove unit of measurement. 

Best alternative for complete switchover is update the build payload function to include creation of a ‘’’type’’’ or equivalent attribute for all instances of check-button-card and follow it with a breaking change release to remove the unit component.

**Comment by Gluwc** [comment]
What about using `device_class` as the type definition instead of `type`? The device class is already used by other sensors to define the type (`motion`,`illuminance`, etc)

**Comment by Gluwc** [comment]
I guess it also shouldn't be too hard to let the card auto update the sensor attributes. It could just check for `device_class` first if it doesn't exist check for `unit_of_measurement` then update the payload.
This should only break possible edge cases where someone actually uses the `unit_of_measurement` somehow.

**Comment by jeremywillans** [comment]
Yeah that’s a good plan. add the class to the payload and update the sensor checks for class or unit options. It might be worth keeping the unit option if people use this for a reason? I just added a new option to remove this.

Can also remove the timestamp checks in a later release 

When I get a change I would also like to add a timeout_seconds attribute to calculate the seconds for the timeout (like the severity seconds entry) this will making update the timeout timestamp via matt publish easier to achieve.

**Comment by Gluwc** [comment]
Is the `unit` config option still required if the `unit_of_measurement` is removed from the attributes? I'd rather not add this config option if it's obsolete.

**Comment by jeremywillans** [comment]
Yeah fair call, let me update then code. The change to using device class requires re-deployment of the mqtt config data (as it’s not in the click payload) so I’m making sure to keep backwards compatibility for existing sensors leveraging the timestamp unit of measurement

**Comment by Gluwc** [comment]
Are there still any changes you want to make? I'd like to integrate this soon, but not sure if you're still working on it.

**Comment by jeremywillans** [comment]
Sorry sick kids were keeping me occupied. I’ll get this done tomorrow ready for review.

**Comment by Gluwc** [comment]
No worries, I'm not in a hurry. Just wanted to make sure I don't integrate outdated stuff.

**Comment by jeremywillans** [comment]
I've implemented the changes. Device_class will be required from this version onwards (breaking change) however existing sensors will have the option of updating their settings rather than requiring remove/recreate.

image

I have kept the unit option, however its now disabled by default and adding unit: true will result in the payload being built with unit_of_measurement if someone has an existing requirement for it.

Let me know your thoughts.

EDIT - Added extra fix for the timeout_timestamp calculation, noticed when recalculating value during an undo update.

**Pull request merged**
